import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import React from "react";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type PropsLayout = {
    children: React.ReactNode;
}

export default function RootLayout({children}: Readonly<PropsLayout>) {
    return (
        <html lang="en">
        <body className={cn(
            "!min-h-screen font-sans antialiased",
            inter.variable
        )}>{children}</body>
        </html>
    );
}
